name: Bungee
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.14.1+3
  image_picker: ^0.6.7+11
  firebase_storage: ^4.0.1
  firebase_auth: ^0.18.1+2
  google_sign_in: ^4.5.4
  geolocator: ^6.0.0+4
  geocoder: ^0.2.1
  uuid: ^2.2.2
  image: ^2.1.18
  animator: ^2.0.1
  path_provider: ^1.6.18
  firebase_messaging: ^7.0.3
  timeago: ^2.0.27
  cached_network_image: ^2.3.2+1
  flutter_svg: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
  assets:
    - assets/images/google_signin_button.png
    - assets/images/upload.svg
    - assets/images/search.svg
    - assets/images/activity_feed.svg
    - assets/images/no_content.svg
